// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"

	"github.com/UtkarshVerma/qgmail/auth"
	"github.com/spf13/cobra"
)

var usersSettingsSendAsSmimeInfoGet = &cobra.Command{
	Use: "users.settings.sendAs.smimeInfo.get <userId> <sendAsEmail> <id>",
	Short: "Gets the specified S/MIME config for the specified send-as alias.",
	Long: "userId: The user's email address. The special value `me` can be used to indicate the authenticated user.\nsendAsEmail: The email address that appears in the `From:` header for mail sent using this alias.\nid: The immutable ID for the SmimeInfo.\n",
	DisableFlagsInUseLine: true,
	Args: cobra.ExactValidArgs(3),
	Run: func(cmd *cobra.Command, args []string) {
		if err := auth.ReadToken(tokenFile); err != nil {
			fmt.Println("Error: Authorization token not found. Please authorize qGmail using 'qgmail auth'.")
			os.Exit(1)
		}

		service, err := auth.NewGmailService()
		cobra.CheckErr(err)

		val, err := service.Users.Settings.SendAs.SmimeInfo.Get(args[0], args[1], args[2]).Do()
		cobra.CheckErr(err)
		fmt.Println(val)
	},
}

func init() {
	requestCmd.AddCommand(usersSettingsSendAsSmimeInfoGet)
}
