// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"

	"github.com/UtkarshVerma/qgmail/auth"
	"github.com/spf13/cobra"
)

var usersMessagesAttachmentsGet = &cobra.Command{
	Use: "users.messages.attachments.get <userId> <messageId> <id>",
	Short: "Gets the specified message attachment.",
	Long: "userId: The user's email address. The special value `me` can be used to indicate the authenticated user.\nmessageId: The ID of the message containing the attachment.\nid: The ID of the attachment.\n",
	DisableFlagsInUseLine: true,
	Args: cobra.ExactValidArgs(3),
	Run: func(cmd *cobra.Command, args []string) {
		if err := auth.ReadToken(tokenFile); err != nil {
			fmt.Println("Error: Authorization token not found. Please authorize qGmail using 'qgmail auth'.")
			os.Exit(1)
		}

		service, err := auth.NewGmailService()
		cobra.CheckErr(err)

		val, err := service.Users.Messages.Attachments.Get(args[0], args[1], args[2]).Do()
		cobra.CheckErr(err)
		fmt.Println(val)
	},
}

func init() {
	requestCmd.AddCommand(usersMessagesAttachmentsGet)
}
