// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"

	"github.com/UtkarshVerma/qgmail/auth"
	"github.com/spf13/cobra"
)

var usersSettingsSendAsSmimeInfoList = &cobra.Command{
	Use: "users.settings.sendAs.smimeInfo.list <userId> <sendAsEmail>",
	Short: "Lists S/MIME configs for the specified send-as alias.",
	Long: "userId: The user's email address. The special value `me` can be used to indicate the authenticated user.\nsendAsEmail: The email address that appears in the `From:` header for mail sent using this alias.\n",
	DisableFlagsInUseLine: true,
	Args: cobra.ExactValidArgs(2),
	Run: func(cmd *cobra.Command, args []string) {
		if err := auth.ReadToken(tokenFile); err != nil {
			fmt.Println("Error: Authorization token not found. Please authorize qGmail using 'qgmail auth'.")
			os.Exit(1)
		}

		service, err := auth.NewGmailService()
		cobra.CheckErr(err)

		val, err := service.Users.Settings.SendAs.SmimeInfo.List(args[0], args[1]).Do()
		cobra.CheckErr(err)
		fmt.Println(val)
	},
}

func init() {
	requestCmd.AddCommand(usersSettingsSendAsSmimeInfoList)
}
