// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"
	"encoding/json"

	"github.com/UtkarshVerma/qgmail/auth"
	"github.com/spf13/cobra"
)

var usersSettingsSendAsGet = &cobra.Command{
	Use: "users.settings.sendAs.get <userId> <sendAsEmail>",
	Short: "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
	Long: "userId: User's email address. The special value `me` can be used to indicate the authenticated user.\nsendAsEmail: The send-as alias to be retrieved.\n",
	DisableFlagsInUseLine: true,
	Args: cobra.ExactValidArgs(2),
	Run: func(cmd *cobra.Command, args []string) {
		if err := auth.ReadToken(tokenFile); err != nil {
			fmt.Println("Error: Authorization token not found. Please authorize qGmail using 'qgmail auth'.")
			os.Exit(1)
		}

		service, err := auth.NewGmailService()
		cobra.CheckErr(err)

		val, err := service.Users.Settings.SendAs.Get(args[0], args[1]).Do()
		cobra.CheckErr(err)

		jsonData, _ := json.Marshal(val)
		fmt.Println(string(jsonData))
	},
}

func init() {
	requestCmd.AddCommand(usersSettingsSendAsGet)
}
