// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"

	"github.com/UtkarshVerma/qgmail/auth"
	"github.com/spf13/cobra"
)

var usersSettingsFiltersList = &cobra.Command{
	Use: "users.settings.filters.list <userId>",
	Short: "Lists the message filters of a Gmail user.",
	Long: "userId: User's email address. The special value `me` can be used to indicate the authenticated user.\n",
	DisableFlagsInUseLine: true,
	Args: cobra.ExactValidArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		if err := auth.ReadToken(tokenFile); err != nil {
			fmt.Println("Error: Authorization token not found. Please authorize qGmail using 'qgmail auth'.")
			os.Exit(1)
		}

		service, err := auth.NewGmailService()
		cobra.CheckErr(err)

		val, err := service.Users.Settings.Filters.List(args[0]).Do()
		cobra.CheckErr(err)
		fmt.Println(val)
	},
}

func init() {
	requestCmd.AddCommand(usersSettingsFiltersList)
}
