// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"

	"github.com/UtkarshVerma/qgmail/auth"
	"github.com/spf13/cobra"
)

var usersSettingsDelegatesGet = &cobra.Command{
	Use: "users.settings.delegates.get <userId> <delegateEmail>",
	Short: "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
	Long: "userId: User's email address. The special value `me` can be used to indicate the authenticated user.\ndelegateEmail: The email address of the user whose delegate relationship is to be retrieved.\n",
	DisableFlagsInUseLine: true,
	Args: cobra.ExactValidArgs(2),
	Run: func(cmd *cobra.Command, args []string) {
		if err := auth.ReadToken(tokenFile); err != nil {
			fmt.Println("Error: Authorization token not found. Please authorize qGmail using 'qgmail auth'.")
			os.Exit(1)
		}

		service, err := auth.NewGmailService()
		cobra.CheckErr(err)

		val, err := service.Users.Settings.Delegates.Get(args[0], args[1]).Do()
		cobra.CheckErr(err)
		fmt.Println(val)
	},
}

func init() {
	requestCmd.AddCommand(usersSettingsDelegatesGet)
}
