// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"

	"github.com/UtkarshVerma/qgmail/auth"
	"github.com/spf13/cobra"
)

var usersSettingsForwardingAddressesGet = &cobra.Command{
	Use: "users.settings.forwardingAddresses.get <userId> <forwardingEmail>",
	Short: "Gets the specified forwarding address.",
	Long: "userId: User's email address. The special value `me` can be used to indicate the authenticated user.\nforwardingEmail: The forwarding address to be retrieved.\n",
	DisableFlagsInUseLine: true,
	Args: cobra.ExactValidArgs(2),
	Run: func(cmd *cobra.Command, args []string) {
		if err := auth.ReadToken(tokenFile); err != nil {
			fmt.Println("Error: Authorization token not found. Please authorize qGmail using 'qgmail auth'.")
			os.Exit(1)
		}

		service, err := auth.NewGmailService()
		cobra.CheckErr(err)

		val, err := service.Users.Settings.ForwardingAddresses.Get(args[0], args[1]).Do()
		cobra.CheckErr(err)
		fmt.Println(val)
	},
}

func init() {
	requestCmd.AddCommand(usersSettingsForwardingAddressesGet)
}
